name: esm_catalog_utils_ci
channels:
  - conda-forge
dependencies:
  - black
  - cftime
  - dask
  - flake8
  - fsspec<2023.3.0
  - intake
  - intake-esm
  - isort
  - mypy
  - netCDF4
  - numpy
  - packaging
  - pandas
  - pytest
  - types-pyyaml
  - xarray
  - zarr<2.15.0
